# Generated by Django 3.2.7 on 2022-01-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=200)),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=200)),
                ('gender', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('country', models.TextField(default='')),
                ('state', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('zip', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
