# Generated by Django 3.2.7 on 2022-01-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_data',
            name='join_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
